AppBundle_index:
    path: /
    defaults: { _controller: "App\\Controller\\PageController::indexAction" }
    requirements:
        methods:  GET

next:
    path: /{i}
    defaults: { _controller: "App\\Controller\\PageController::indexAction" }
    requirements:
      methods:  GET
      i: \d+
