index:
  path: /lucky/number
  controller: App\Controller\TestController::number

BloggerBlogBundle_homepage:
  path:     /
  defaults: { _controller: "BloggerBlogBundle:Page:index" }
  requirements:
    methods:  GET

BloggerBlogBundle_about:
  path:   /about
  defaults: { _controller: "BloggerBlogBundle:Page:about" }
  requirements:
    methods:  GET